name: Delete Secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: The name of the secret to delete
        required: true
      environment:
        description: The environment to delete the secret from
        type: choice
        options:
          - development
          - production

jobs:
  delete-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete secret from dotenv file
        uses: ammarlakis/gitsops/action/delete@master
        with:
          secret_name: ${{ github.event.inputs.secret_name }}
          secret_file_path: myproject/${{ github.event.inputs.environment }}-secrets.env
          additional_args: '--kms=arn:aws:kms:us-east-1:905418242537:key/2fc869fe-3bcd-4b84-8f5d-f1ff33a4b470'

      - name: Check for changes
        id: check_changes
        run: |
          git add myproject/${{ github.event.inputs.environment }}-secrets.env

          # Check if there are any changes to commit and set output accordingly
          if [ -n "$(git diff --cached)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name "${{ github.event.sender.login }}"
          git config user.email "${{ github.event.sender.email }}"

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git commit -m "Delete secret: ${{ github.event.inputs.secret_name }}"

      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git push origin
