name: Read Secrets and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to read secrets from
        type: choice
        options:
          - development
          - production

jobs:
  read-secrets-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read secrets from dotenv file
        uses: ammarlakis/gitsops/action/read@master
        with:
          secret_file_path: myproject/${{ github.event.inputs.environment }}-secrets.env
          include_pattern: ".*"  # Reads all secrets

      - name: Run Deploy Script
        run: |
          myproject/deploy.sh
