name: Read Secrets and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to read secrets from
        type: choice
        options:
          - development
          - production

jobs:
  read-secrets-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read secrets from dotenv file
        uses: ammarlakis/gitsops/action/read@master
        with:
          secret_file_path: myproject/${{ github.event.inputs.environment }}-secrets.env
          include_pattern: ".*"  # Reads all secrets
          additional_args: '--kms=arn:aws:kms:us-east-1:905418242537:key/2fc869fe-3bcd-4b84-8f5d-f1ff33a4b470'

      - name: Run Deploy Script
        run: |
          sh myproject/deploy.sh
