name: Upsert Secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: The name of the secret to add or update
        required: true
      secret_value:
        description: The value of the secret
        required: true
      environment:
        description: THe environment to update its secrets
        type: choice
        options:
          - development
          - production

jobs:
  upsert-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upsert secret in dotenv file
        uses: ammarlakis/gitsops/action/upsert@master
        with:
          secret_name: ${{ github.event.inputs.secret_name }}
          secret_value: ${{ github.event.inputs.secret_value }}
          secret_file_path: myproject/${{ github.event.inputs.environment }}-secrets.env
          additional_args: '--kms=arn:aws:kms:us-east-1:905418242537:key/2fc869fe-3bcd-4b84-8f5d-f1ff33a4b470'

      - name: Check for changes
        id: check_changes
        run: |
          git add myproject/${{ github.event.inputs.environment }}-secrets.env

          # Check if there are any changes to commit and set output accordingly
          if [ -n "$(git diff --cached)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name ${{ github.event.sender.name }}
          git config user.email ${{ github.event.sender.email }}

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git commit -m "Upsert secret: ${{ github.event.inputs.secret_name }}"

      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git push origin
